project:
  type: website

website:
  description: "Lucas Hudson - Data Science, Open Source AI Projects, and Blog."
  site-url: https://lucas-hudsn.github.io
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lucas-hudsn
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-hudson-0a1384183/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



