<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lucas Hudson">
<meta name="dcterms.date" content="2026-03-07">

<title>Fine-Tuning EmbeddingGemma-300M for Legal Information Retrieval – lucas-hudsn</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-872e900a155e990e89d7b6fcf623f4fb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">lucas-hudsn</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lucas-hudsn"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/lucas-hudson-0a1384183/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fine-Tuning EmbeddingGemma-300M for Legal Information Retrieval</h1>
  <div class="quarto-categories">
    <div class="quarto-category">ML</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lucas Hudson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="fine-tuning-an-embedding-model-for-legal-information-retrieval" class="level1">
<h1>Fine-Tuning an Embedding Model for Legal Information Retrieval</h1>
<p><strong>Competition:</strong> <a href="https://www.kaggle.com/competitions/llm-agentic-legal-information-retrieval">Kaggle — LLM Agentic Legal Information Retrieval</a> <strong>My Role:</strong> Embedding model (part of a group project with colleagues) <strong>Model:</strong> <code>unsloth/embeddinggemma-300m</code> fine-tuned with LoRA <strong>Hardware:</strong> Apple Silicon Mac (MPS backend, no CUDA)</p>
<hr>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This was a group Kaggle competition where the core task was legal information retrieval: given a query from a legal document, retrieve the most relevant laws or court considerations from a corpus. My responsibility was the embedding model — fine-tuning a dense retrieval model that could learn what “relevant” means specifically in the German legal domain.</p>
<p>The core idea was to take a pre-trained embedding model, feed it domain-specific (query, relevant passage) pairs, and use contrastive learning to push relevant query-document pairs closer together in vector space. I also wanted to use this as an opportunity to explore whether embedding fine-tuning on Apple Silicon was viable, since all my available compute was a MacBook — no cloud GPU budget.</p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><strong>Unsloth EmbeddingGemma guide:</strong> https://unsloth.ai/docs/new/embedding-finetuning — the primary recipe I followed for the training approach, LoRA configuration, and loss function.</li>
<li><strong>mlx-tune (ARahim3):</strong> https://github.com/ARahim3/mlx-tune — a reference for adapting Unsloth-style training pipelines to run on Apple Silicon using PyTorch MPS instead of CUDA/Triton. The core insight from this project is using MPS as a prototyping bridge: develop locally, migrate to cloud for production scale.</li>
</ul>
<hr>
</section>
<section id="data-preparation-etl.py" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-etl.py">Data Preparation (<code>etl.py</code>)</h2>
<p>The competition provides three files: <code>train.csv</code> (queries with gold citation annotations), <code>laws_de.csv</code> (German law passages), and <code>court_considerations.csv</code> (court ruling passages). The gold citations in <code>train.csv</code> are semicolon-separated and can reference both laws and court considerations.</p>
<p>The ETL pipeline does the following:</p>
<ol type="1">
<li><strong>Explodes multi-citation rows</strong> — each row in <code>train.csv</code> can have multiple gold citations joined by <code>;</code>. I split and explode these so each (query, citation) pair becomes its own row.</li>
<li><strong>Merges against both corpora</strong> — the exploded rows are inner-joined against <code>laws_de.csv</code> on <code>citation</code>, then separately inner-joined against <code>court_considerations.csv</code>, and the results are concatenated. This produces a flat table of <code>(query, text)</code> pairs where <code>text</code> is the actual passage content for that citation.</li>
<li><strong>Outputs <code>joined_data.csv</code></strong> — this becomes the training data for the model.</li>
</ol>
<p>The inner join approach means only queries with citations that exist in the corpora are kept. This is a reasonable tradeoff: it ensures every training pair is a genuine (query, ground-truth passage) pair, at the cost of dropping queries whose citations couldn’t be matched.</p>
<hr>
</section>
<section id="training-pipeline-train.py" class="level2">
<h2 class="anchored" data-anchor-id="training-pipeline-train.py">Training Pipeline (<code>train.py</code>)</h2>
<section id="step-1-device-detection" class="level3">
<h3 class="anchored" data-anchor-id="step-1-device-detection">Step 1: Device Detection</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> torch.backends.mps.is_available():</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    device <span class="op">=</span> <span class="st">"mps"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> torch.cuda.is_available():</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    device <span class="op">=</span> <span class="st">"cuda"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    device <span class="op">=</span> <span class="st">"cpu"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The script detects the available backend at runtime — MPS for Apple Silicon, CUDA for cloud/GPU machines, CPU as a fallback. This was deliberately written to be portable, following the mlx-tune philosophy: develop and validate locally on Mac, then run identical code on a cloud GPU. The actual Unsloth CUDA kernels aren’t used here because they require CUDA; instead, standard PyTorch MPS handles the GPU acceleration on Mac.</p>
</section>
<section id="step-2-data-loading-and-splitting" class="level3">
<h3 class="anchored" data-anchor-id="step-2-data-loading-and-splitting">Step 2: Data Loading and Splitting</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/joined_data.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">"query"</span>, <span class="st">"text"</span>])</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[[<span class="st">"query"</span>, <span class="st">"text"</span>]].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>train_end <span class="op">=</span> <span class="bu">int</span>(n <span class="op">*</span> <span class="fl">0.70</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>eval_end  <span class="op">=</span> <span class="bu">int</span>(n <span class="op">*</span> <span class="fl">0.85</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The dataset is split 70 / 15 / 15 into train, eval, and test. Only the <code>query</code> and <code>text</code> columns are kept — everything else (like the citation ID) is irrelevant to the model. The eval set drives the <code>InformationRetrievalEvaluator</code> during training, and the test set is held out for a final pre/post comparison.</p>
</section>
<section id="step-3-model-selection-embeddinggemma-300m" class="level3">
<h3 class="anchored" data-anchor-id="step-3-model-selection-embeddinggemma-300m">Step 3: Model Selection — EmbeddingGemma 300M</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>MODEL_NAME <span class="op">=</span> <span class="st">"unsloth/embeddinggemma-300m"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SentenceTransformer(MODEL_NAME, device<span class="op">=</span>device)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>I chose <code>unsloth/embeddinggemma-300m</code> for several reasons:</p>
<ul>
<li><strong>Size fits on-device memory.</strong> At 300M parameters, it runs comfortably on Apple Silicon with MPS. Larger embedding models (e.g.&nbsp;7B) would be impractical without cloud compute.</li>
<li><strong>Strong pre-trained representations.</strong> EmbeddingGemma is derived from Google’s Gemma family, which has strong language understanding. For a specialised domain like German law, you want a model with good multilingual/legal grounding before fine-tuning.</li>
<li><strong>Unsloth’s recipe is proven.</strong> The Unsloth documentation specifically targets this model for LoRA embedding fine-tuning with MultipleNegativesRankingLoss, so I was following a validated path rather than experimenting with an untested combination.</li>
</ul>
</section>
<section id="step-4-lora-configuration" class="level3">
<h3 class="anchored" data-anchor-id="step-4-lora-configuration">Step 4: LoRA Configuration</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lora_config <span class="op">=</span> LoraConfig(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    r<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    lora_alpha<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    target_modules<span class="op">=</span>[<span class="st">"q_proj"</span>, <span class="st">"k_proj"</span>, <span class="st">"v_proj"</span>, <span class="st">"o_proj"</span>],</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    lora_dropout<span class="op">=</span><span class="fl">0.0</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    bias<span class="op">=</span><span class="st">"none"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    task_type<span class="op">=</span>TaskType.FEATURE_EXTRACTION,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>model[<span class="dv">0</span>].auto_model <span class="op">=</span> get_peft_model(model[<span class="dv">0</span>].auto_model, lora_config)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>LoRA (Low-Rank Adaptation) freezes the base model weights and injects small trainable rank-decomposition matrices into selected layers. The key decisions here:</p>
<ul>
<li><strong><code>r=16</code>, <code>lora_alpha=32</code></strong> — rank 16 gives a reasonable expressivity-to-parameter trade-off. The alpha/rank ratio of 2 is a common default that scales the LoRA updates to a sensible magnitude.</li>
<li><strong>Targeting all four attention projections</strong> (<code>q_proj</code>, <code>k_proj</code>, <code>v_proj</code>, <code>o_proj</code>) — for an embedding model, the attention mechanism is the primary driver of contextual representations. Adapting all four projections gives the model maximum flexibility to reshape how it attends to tokens, which is where domain-specific patterns are learned.</li>
<li><strong><code>lora_dropout=0.0</code></strong> — the dataset is small and the model is already regularised via the contrastive loss structure. Adding dropout here would have added noise without clear benefit.</li>
<li><strong><code>task_type=TaskType.FEATURE_EXTRACTION</code></strong> — correctly signals to PEFT that this is an embedding task, not a generation task.</li>
<li><strong>LoRA instead of full fine-tuning</strong> — full fine-tuning a 300M model on Mac was feasible in theory but would have been significantly slower and risked catastrophic forgetting of the general representations. LoRA keeps the base model frozen, meaning the legal domain knowledge is added on top rather than overwriting the general language understanding.</li>
</ul>
</section>
<section id="step-5-information-retrieval-evaluator" class="level3">
<h3 class="anchored" data-anchor-id="step-5-information-retrieval-evaluator">Step 5: Information Retrieval Evaluator</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_ir_evaluator(ds: Dataset, name: <span class="bu">str</span>) <span class="op">-&gt;</span> InformationRetrievalEvaluator:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    queries       <span class="op">=</span> {i: ds[i][<span class="st">"query"</span>] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(ds))}</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    corpus        <span class="op">=</span> {i: ds[i][<span class="st">"text"</span>]  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(ds))}</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    relevant_docs <span class="op">=</span> {i: {i}            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(ds))}</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> InformationRetrievalEvaluator(...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>InformationRetrievalEvaluator</code> runs full retrieval evaluation at each checkpoint: it embeds all queries and corpus passages, then measures how well the model ranks the ground-truth passage for each query. The evaluator gives nDCG@10, MRR@10, MAP@100, and Accuracy@K metrics — all standard IR evaluation metrics.</p>
<p>The <code>relevant_docs = {i: {i}}</code> construction treats each query-passage pair as its own isolated retrieval problem: query <code>i</code> has exactly one relevant document, which is corpus entry <code>i</code>. This is appropriate for this dataset because the training pairs are direct (query → passage) correspondences from the citation matching in the ETL step.</p>
<p>I also run a baseline evaluation on the test set before training starts, so I can quantify exactly how much improvement fine-tuning provides.</p>
</section>
<section id="step-6-loss-function-multiplenegativesrankingloss" class="level3">
<h3 class="anchored" data-anchor-id="step-6-loss-function-multiplenegativesrankingloss">Step 6: Loss Function — MultipleNegativesRankingLoss</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> losses.MultipleNegativesRankingLoss(model)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>train_for_loss <span class="op">=</span> train_dataset.rename_column(<span class="st">"query"</span>, <span class="st">"anchor"</span>).rename_column(<span class="st">"text"</span>, <span class="st">"positive"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>MultipleNegativesRankingLoss (MNRL) is the standard choice for embedding fine-tuning with (query, positive_passage) pairs. Within each batch, every other example’s positive passage is treated as a negative for the current query. This means:</p>
<ul>
<li><strong>No need to mine hard negatives</strong> — the in-batch negatives are automatically created, which keeps the data pipeline simple.</li>
<li><strong><code>BatchSamplers.NO_DUPLICATES</code></strong> — ensures no two examples in a batch share the same query or passage, which is required for MNRL to work correctly (duplicate passages would be incorrectly treated as negatives when they’re actually positives).</li>
<li><strong>Effective batch of 32</strong> — with <code>per_device_train_batch_size=4</code> and <code>gradient_accumulation_steps=8</code>, the model accumulates gradients over 32 examples before updating. Larger effective batches mean more in-batch negatives per update, which makes MNRL more effective. This was the main lever to improve training quality within the memory constraints of MPS.</li>
</ul>
</section>
<section id="step-7-training-arguments" class="level3">
<h3 class="anchored" data-anchor-id="step-7-training-arguments">Step 7: Training Arguments</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>training_args <span class="op">=</span> SentenceTransformerTrainingArguments(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    max_steps<span class="op">=</span><span class="dv">200</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">2e-5</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    warmup_ratio<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    lr_scheduler_type<span class="op">=</span><span class="st">"cosine"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    gradient_checkpointing<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    bf16<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    fp16<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    dataloader_pin_memory<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Several of these were forced by the MPS constraints:</p>
<ul>
<li><strong><code>bf16=False</code>, <code>fp16=False</code></strong> — MPS does not support mixed-precision training reliably. Training in float32 costs memory and speed but was the only stable option.</li>
<li><strong><code>dataloader_pin_memory=False</code></strong> — pinned memory is a CUDA-specific optimisation that is unsupported on MPS and causes errors if enabled.</li>
<li><strong><code>gradient_checkpointing=True</code></strong> — trades compute for memory by recomputing intermediate activations during the backward pass. On a memory-constrained Mac, this was necessary to keep the training from OOM-crashing.</li>
<li><strong><code>max_steps=200</code></strong> — with only 200 steps I was primarily validating the pipeline and checking that the model could learn. Given more compute, I’d have run for far longer.</li>
<li><strong><code>lr_scheduler_type="cosine"</code> with <code>warmup_ratio=0.05</code></strong> — cosine decay is a robust default that gradually reduces the learning rate as training progresses, reducing the risk of unstable updates late in training. The 5% warmup prevents large gradient spikes in the first few steps.</li>
</ul>
</section>
<section id="step-8-mps-cache-callback" class="level3">
<h3 class="anchored" data-anchor-id="step-8-mps-cache-callback">Step 8: MPS Cache Callback</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MpsCacheCallback(TrainerCallback):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> on_evaluate(<span class="va">self</span>, args, state, control, <span class="op">**</span>kwargs):</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> torch.backends.mps.is_available():</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            torch.mps.empty_cache()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A small but necessary quality-of-life fix: the evaluator runs full corpus and query encoding on MPS, which consumes significant memory. Without explicitly clearing the MPS cache after each evaluation, memory fragmentation would accumulate and eventually crash the process. This callback calls <code>torch.mps.empty_cache()</code> after every eval step to reclaim that memory.</p>
</section>
<section id="step-9-post-training-evaluation-and-saving" class="level3">
<h3 class="anchored" data-anchor-id="step-9-post-training-evaluation-and-saving">Step 9: Post-Training Evaluation and Saving</h3>
<p>After training, the script re-evaluates on the held-out test set and computes the delta against the pre-training baseline. Both the baseline and post-training results are serialised to <code>output/test_results.json</code>, and the fine-tuned model (with LoRA adapters merged) is saved to <code>embeddinggemma_legal_lora/</code>.</p>
<hr>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The model was trained for 200 steps (~2.74 epochs) with eval checkpoints every 50 steps. The full metric progression on the eval set is shown below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Epoch</th>
<th>nDCG@10</th>
<th>MRR@10</th>
<th>MAP@100</th>
<th>Acc@1</th>
<th>Acc@5</th>
<th>Acc@10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50</td>
<td>0.69</td>
<td>0.2585</td>
<td>0.2024</td>
<td>0.2191</td>
<td>0.1145</td>
<td>0.3112</td>
<td>0.4418</td>
</tr>
<tr class="even">
<td>100</td>
<td>1.37</td>
<td>0.2707</td>
<td>0.2146</td>
<td>0.2324</td>
<td>0.1265</td>
<td>0.3233</td>
<td>0.4538</td>
</tr>
<tr class="odd">
<td>150</td>
<td>2.06</td>
<td>0.2743</td>
<td>0.2175</td>
<td>0.2356</td>
<td>0.1285</td>
<td>0.3293</td>
<td>0.4598</td>
</tr>
<tr class="even">
<td>200</td>
<td>2.74</td>
<td><strong>0.2736</strong></td>
<td><strong>0.2165</strong></td>
<td><strong>0.2346</strong></td>
<td><strong>0.1265</strong></td>
<td><strong>0.3273</strong></td>
<td><strong>0.4598</strong></td>
</tr>
</tbody>
</table>
<section id="metric-improvements-step-50-step-200" class="level3">
<h3 class="anchored" data-anchor-id="metric-improvements-step-50-step-200">Metric Improvements (step 50 → step 200)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Start</th>
<th>End</th>
<th>Delta</th>
<th>% Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nDCG@10</td>
<td>0.2585</td>
<td>0.2736</td>
<td>+0.0151</td>
<td>+5.8%</td>
</tr>
<tr class="even">
<td>MRR@10</td>
<td>0.2024</td>
<td>0.2165</td>
<td>+0.0141</td>
<td>+7.0%</td>
</tr>
<tr class="odd">
<td>MAP@100</td>
<td>0.2191</td>
<td>0.2346</td>
<td>+0.0155</td>
<td>+7.1%</td>
</tr>
<tr class="even">
<td>Acc@1</td>
<td>0.1145</td>
<td>0.1265</td>
<td>+0.0120</td>
<td>+10.5%</td>
</tr>
<tr class="odd">
<td>Acc@3</td>
<td>0.2450</td>
<td>0.2651</td>
<td>+0.0201</td>
<td>+8.2%</td>
</tr>
<tr class="even">
<td>Acc@5</td>
<td>0.3112</td>
<td>0.3273</td>
<td>+0.0161</td>
<td>+5.2%</td>
</tr>
<tr class="odd">
<td>Acc@10</td>
<td>0.4418</td>
<td>0.4598</td>
<td>+0.0181</td>
<td>+4.1%</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="assessment" class="level2">
<h2 class="anchored" data-anchor-id="assessment">Assessment</h2>
<section id="what-worked" class="level3">
<h3 class="anchored" data-anchor-id="what-worked">What Worked</h3>
<p>The pipeline itself was a success. Getting LoRA embedding fine-tuning to run stably on MPS — with gradient checkpointing, cache management, and a full IR evaluator — required navigating several Apple Silicon-specific constraints that aren’t well-documented. The training was stable throughout: loss dropped consistently from ~0.63 at step 10 to ~0.44 by the end, and every retrieval metric improved monotonically from checkpoint to checkpoint (at least up to step 150).</p>
<p>The metric gains are modest but real. A ~7% improvement in MRR@10 and MAP@100 from 200 steps is encouraging, and the Acc@1 gain of 10.5% is meaningful — it means the model is substantially more likely to rank the exact correct passage first.</p>
<p>The eval loss also decreased steadily (0.492 → 0.419), confirming the model was genuinely learning and not just overfitting to the training set. The fact that eval metrics track training loss closely suggests the LoRA adapter is generalising rather than memorising.</p>
</section>
<section id="what-didnt-work" class="level3">
<h3 class="anchored" data-anchor-id="what-didnt-work">What Didn’t Work</h3>
<p>The absolute performance numbers are low. An nDCG@10 of 0.27 and Acc@1 of 0.13 means the model fails to rank the correct passage first the vast majority of the time. For a production retrieval system this would be inadequate. There are a few likely causes:</p>
<ol type="1">
<li><p><strong>Only 200 steps.</strong> The metrics had not plateaued by step 150 — the best nDCG@10 (0.2743) actually appeared at step 150, not step 200, hinting that more training with proper validation-based early stopping would have been beneficial. This was a hard constraint of my local hardware and the time I had available.</p></li>
<li><p><strong>The IR evaluator construction is too easy and too hard at the same time.</strong> The <code>relevant_docs = {i: {i}}</code> mapping means the retrieval problem is evaluated by searching only ~15% of the dataset as the corpus. With a small eval corpus, there’s less discrimination needed — but the “ground truth” is also narrowly defined as a single exact passage. In reality, multiple passages can be relevant to the same legal query, and this setup doesn’t capture that.</p></li>
<li><p><strong>No hard negative mining.</strong> MNRL with random in-batch negatives is the simplest contrastive learning approach. In specialised domains like law, where many passages are superficially similar (same legal area, overlapping terminology), hard negatives — passages that are plausible but wrong — are important for teaching the model to make fine-grained distinctions. I didn’t implement this.</p></li>
<li><p><strong>Float32 training on MPS.</strong> Not using mixed precision (bf16 or fp16) significantly slowed training and limited the batch size I could afford. On CUDA, I could have run with bf16 and a larger effective batch, which generally improves MNRL quality.</p></li>
<li><p><strong>No baseline comparison in the report.</strong> The <code>test_results.json</code> wasn’t captured (the baseline evaluation ran at startup but the delta summary wasn’t persisted in the report), so I can’t quote the exact improvement from zero-shot to fine-tuned on the test set — only the progression across eval checkpoints during training.</p></li>
</ol>
</section>
<section id="what-i-would-do-differently" class="level3">
<h3 class="anchored" data-anchor-id="what-i-would-do-differently">What I Would Do Differently</h3>
<ul>
<li><strong>Run on cloud GPU with the actual Unsloth library.</strong> The mlx-tune philosophy of prototyping locally and then migrating is sound, and I validated the pipeline locally. The next step would be to spin up a Colab or cloud instance and run with the real Unsloth <code>FastSentenceTransformer</code>, which would give 1.8–3.3x speed improvement and enable bf16 — allowing more steps, larger effective batch sizes, and faster iteration.</li>
<li><strong>Train for significantly more steps</strong> with validation-based early stopping rather than a fixed step cap.</li>
<li><strong>Mine hard negatives</strong> using BM25 or a zero-shot embedding model to find plausible but incorrect passages, then feed those as explicit negatives to the loss function.</li>
<li><strong>Experiment with QLoRA</strong> (4-bit quantisation + LoRA) to fit a larger base model into the same memory envelope, potentially giving better starting representations.</li>
<li><strong>Fix the test set delta reporting</strong> — the script saves <code>test_results.json</code> with baseline and post-training metrics, but the report generation step wasn’t plumbed to read it. Adding that would complete the picture.</li>
</ul>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This project achieved its main goals: I built and validated an end-to-end embedding fine-tuning pipeline on Apple Silicon, proved that LoRA adapter training for dense retrieval is feasible with MPS as a compute backend, and delivered measurable retrieval improvements on legal data. The absolute performance numbers leave significant room for improvement, but given the hardware constraints and the 200-step training budget, the consistent upward trend across all metrics demonstrates the approach is sound. The natural next step is scaling the same pipeline to cloud GPU hardware with full Unsloth support.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lucas-hudsn\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>